name = "dynamics"
version = "1.0.3"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2022-2024, Jason Christopherson"
description = "A library of routines used for the analysis of dynamic systems."
homepage = "https://github.com/jchristopherson/dynamics"

[library]
source-dir = "src"

[dependencies]
ferror = { git = "https://github.com/jchristopherson/ferror" }
linalg = { git = "https://github.com/jchristopherson/linalg" }
nonlin = { git = "https://github.com/jchristopherson/nonlin" }
diffeq = { git = "https://github.com/jchristopherson/diffeq" }
spectrum = { git = "https://github.com/jchristopherson/spectrum" }
fftpack = { git = "https://github.com/fortran-lang/fftpack" }

[dev-dependencies]
fortran_test_helper = { git = "https://github.com/jchristopherson/fortran_test_helper" }

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[test]]
name = "dynamics_tests"
source-dir = "test"
main = "dynamics_tests.f90"