name: doc-deployment

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes doxygen
        pip install -v ford==6.1.17

    - name: Build Fortran documentation
      run: ford docs.md

    - name: Build C documentation
      run: doxygen c_docs/c-api.doxyfile

    - name: Validate documentation output
      run: |
        test -f doc/index.html
        test -f doc/c-api/index.html

    - uses: JamesIves/github-pages-deploy-action@3.7.1
      if: github.event_name == 'push' && github.repository == 'jchristopherson/dynamics' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/main' )
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: doc
        CLEAN: true